name: Generate Test Plans from Jira Tickets

on:
  workflow_dispatch:
    inputs:
      jira_ticket_ids:
        description: 'Comma-separated Jira ticket IDs (e.g., WYN-1234,WYN-4567)'
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run test plan generator
      env:
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}      # ✅ Moved to secret
        JIRA_TICKET_IDS: ${{ github.event.inputs.jira_ticket_ids }}
      run: python scripts/generatetestplan.py
